"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, Tlali Engrav and <FULL NAME>, this 
programming assignment is my own work and I have not provided this code to 
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: tae695
UT EID 2:
"""

def length_of_longest_substring_n3(s):
    """
    Finds the length of the longest substring without repeating characters
    using a brute force approach (O(N^3)).

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    if not s:
        return 0
    new_val = ''
    vals = []
    m = s
    for _ in s:
        for j in m:
            if j not in new_val:
                new_val += j
            else:
                vals.append(new_val)
                new_val = ''
        m = m[1:]
    max_len = max(vals, key=len)
    return len(max_len)

def length_of_longest_substring_n2(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N^2)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    if not s:
        return 0
    max_len = 0
    str_dict = {}
    m = s
    num = 0
    for _ in s:
        num = 0
        stat = True
        for j in m:
            if j not in str_dict and stat is True:
                str_dict[j] = 1
                num += 1
            else:
                str_dict = {}
                stat = False
            max_len = max(max_len, num)
        m = m[1:]
    return max_len

# TODO: implement this function. You may delete this comment when you are done.
def length_of_longest_substring_n(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list. However, this approach stops early, breaking out of the inner
    loop when a repeating character is found. You may also choose to challenge
    yourself by implementing a sliding window approach.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    pass
