"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, Tlali Engrav and Coen Street, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: tae695
UT EID 2: cms8699
"""

def rail_fence_encode(string, key):
    """
    pre: string is a string of characters and key is a positive
        integer 2 or greater and strictly less than the length
        of string
    post: returns a single string that is encoded with
        rail fence algorithm
    """
    pos = 0
    up = False
    i = 0
    length = len(string)
    final_lst = []
    lst = [['' for _ in range(length)] for _ in range(int(key))]
    for char in string:
        if pos == 0:
            up = False
        if pos == (key - 1):
            up = True
        lst[pos][i] = char

        if up is False:
            pos += 1
        elif up is True:
            pos -= 1
        i += 1
    for row in lst:
        for c in row:
            if c != '':
                final_lst.append(c)
    final = ''.join(final_lst)
    return final

def rail_fence_decode(string, key):
    """
    pre: string is a string of characters and key is a positive
        integer 2 or greater and strictly less than the length
        of string
    post: function returns a single string that is decoded with
        rail fence algorithm
    """
    pos = 0
    up = False
    ind = 0
    i = 0
    char = list(string)
    lst = [['' for _ in range(len(string))] for _ in range(int(key))]
    for _ in string:
        if pos == 0:
            up = False
        if pos == (key - 1):
            up = True
        lst[pos][i] = '-'
        if up is False:
            pos += 1
        elif up is True:
            pos -= 1
        i += 1
    for k in range(key):
        for l in range(len(string)):
            if lst[k][l] == '-':
                lst[k][l] = char[ind]
                ind += 1
    pos = 0
    up = False
    i = 0
    lst_decode = []
    for _ in range(len(string)):
        if pos == 0:
            up = False
        if pos == (key-1):
            up = True
        lst_decode.append(lst[pos][i])
        if up is False:
            pos += 1
        elif up is True:
            pos -= 1
        i += 1
    decoded = ''.join(lst_decode)
    return decoded

def filter_string(string):
    """
    pre: string is a string of characters
    post: function converts all characters to lower case and then
        removes all digits, punctuation marks, and spaces. It
        returns a single string with only lower case characters
    """
    f = string.lower()
    final_s = []
    for char in f:
        if char.isalpha():
            final_s.append(char)
    final = "".join(final_s)
    return final

def encode_character(p, s):
    """
    pre: p is a character in the pass phrase and s is a character
        in the plain text
    post: function returns a single character encoded using the
        Vigenere algorithm. You may not use a 2-D list
    """
    p = ord(p)
    s = ord(s)
    shift = p - 97
    s += shift
    if s > 122:
        j = s - 123
        s = 97 + j
    return chr(s)

def decode_character(p, s):
    """
    pre: p is a character in the pass phrase and s is a character
        in the encrypted text
    post: function returns a single character decoded using the
        Vigenere algorithm. You may not use a 2-D list
    """
    p = ord(p)
    s = ord(s)
    shift = p - 97
    s -= shift
    if s < 97:
        j = s - 96
        s = 122 + j
    return chr(s)

def vigenere_encode(string, phrase):
    """
    pre: string is a string of characters and phrase is a pass phrase
    post: function returns a single string that is encoded with
        Vigenere algorithm
    """
    string = filter_string(string)
    phrase = filter_string(phrase)
    i = 0
    char_str = ''
    for char in string:
        if i >= len(phrase):
            i -= len(phrase)
        char_str += encode_character(phrase[i], char)
        i += 1
    return char_str

def vigenere_decode(string, phrase):
    """
    pre: string is a string of characters and phrase is a pass phrase
    post: function returns a single string that is decoded with
        Vigenere algorithm
    """
    string = filter_string(string)
    phrase = filter_string(phrase)
    i = 0
    char_str = ''
    for char in string:
        if i >= len(phrase):
            i -= len(phrase)
        char_str += decode_character(phrase[i], char)
        i += 1
    return char_str

def main():
    """Main function that reads stdin and runs each cipher"""
    # read the plain text from stdin (terminal/input)
    railfence_str = input()
    # read the key from stdin (terminal/input)
    railfence_key = input()
    # encrypt and print the encoded text using rail fence cipher
    encrypt = rail_fence_encode(railfence_str, int(railfence_key))
    # read encoded text from stdin (terminal/input)
    railencoded = input()
    # read the key from stdin (terminal/input)
    keyencoded = input()
    # decrypt and print the plain text using rail fence cipher
    decrypt = rail_fence_decode(railencoded, int(keyencoded))
    # read the plain text from stdin (terminal/input)
    vig_string = input()
    # read the pass phrase from stdin (terminal/input)
    vig_pass = input()
    # encrypt and print the encoded text using Vigenere cipher
    vigcrypt = vigenere_encode(vig_string, vig_pass)
    # read the encoded text from stdin (terminal/input)
    vig_string_2 = input()
    # read the pass phrase from stdin (terminal/input)
    vig_pass_2 = input()
    # decrypt and print the plain text using Vigenere cipher
    vigdecrypt = vigenere_decode(vig_string_2, vig_pass_2)
    print('Rail Fence Cipher')
    print()
    print('Plain Text:', railfence_str)
    print('Key:', railfence_key)
    print('Encoded Text:', encrypt)
    print()
    print('Encoded Text:', railencoded)
    print('Enter Key:', keyencoded )
    print('Decoded Text:', decrypt)
    print()
    print('Vigenere Cipher')
    print()
    print('Plain Text:', vig_string)
    print('Pass Phrase:', vig_pass)
    print('Encoded Text:', vigcrypt)
    print()
    print('Encoded Text:', vig_string_2)
    print('Pass Phrase:', vig_pass_2)
    print('Decoded Text:', vigdecrypt)

# Do NOT modify the following code.
if __name__ == "__main__":
    main()
