"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, Tlali Engrav and Coen Street, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: tae695
UT EID 2: cms8699
"""


def group_sum(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to the
    given target.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if start >= len(nums):
        return target == 0
    target -= nums[start]
    if group_sum(start + 1, nums, target):
        return True
    target += nums[start]
    if group_sum(start + 1, nums, target):
        return True
    return False

def group_sum_6(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to the
    given target. Additionally, if there is are 6's present in the array, they must all
    be chosen.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if start >= len(nums):
        return target == 0
    if nums[start] == 6: # if there is a 6 it has to be included
        target -= nums[start] 
    # include the first number
    target -= nums[start]
    if group_sum_6(start + 1, nums, target):
        return True
    # Undo choice
    target += nums[start]
    return group_sum_6(start + 1, nums, target)

def group_no_adj(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to
    the given target. Additionally, if a value is chosen, the value immediately after
    (the value adjacent) cannot be chosen.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if start >= len(nums):
        return target == 0
    target -= nums[start]
    if group_no_adj(start + 2, nums, target):
        return True
    target += nums[start]
    if group_no_adj(start + 1, nums, target):
        return True
    return False

def group_sum_5(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to
    the given target. Additionally, if a multiple of 5 is in the array, it must be included
    If the value immediately following a multiple of 5 if 1, it must not be chosen

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if start >= len(nums):
        return target == 0
    if nums[start] % 5 == 0:
        target -= nums[start]
        if nums[start + 1] == 1 or nums[start + 1] % 5 == 0:
            start += 1
    # include the first number
    target -= nums[start]
    if group_sum_5(start + 1, nums, target):
        return True
    # Undo choice
    target += nums[start]
    return group_sum_5(start + 1, nums, target)


def group_sum_clump(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to
    the given target. Additionally, if there is a group of identical numbers in succession,
    they must all be chosen, or none of them must be chosen.
    EX: [1, 2, 2, 2, 5, 2], all three of the middle 2's must be chosen, or none of them must be
    chosen to be included in the sum. One loop is allowed to check for identical numbers.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    i = 1
    if start >= len(nums):
        return target == 0
    if start + i < len(nums) and nums[start] == nums[start + i]:
        target -= nums[start]
        while start + i < len(nums) and nums[start] == nums[start + i]:
            i += 1
            target -= nums[start + i - 1]
        if target >= 0 and group_sum_clump(start + i, nums, target):
            return True
        target += nums[start] * i
    if group_sum_clump(start + i, nums, target):
        return True
    target -= nums[start] * i
    if target >= 0 and group_sum_clump(start + i, nums, target):
        return True
    return False

def split_array(nums):
    """
    Given a list of ints, determine if the numbers can be split evenly into two groups
    The sum of these two groups must be equal
    Write a recursive helper to call from this function

    pre: len(nums) >= 0, nums will only contain ints
    post: return True if nums can be split, False otherwise
    """
    tot = sum(nums)
    val = 0
    lst = []
    if tot % 2 == 0 and sum(nums) != 0:
        target = tot // 2
    elif sum(nums) == 0:
        return True
    else:
        return False
    return tracking(0, nums, target, val, lst)

def tracking(i, nums, target, val, lst):
    tot = sum(lst)
    if i >= len(nums):
        return val == 2
    if target == tot:
        val += 1
    if val == 2:
        return True
    lst.append(nums[i])
    if tracking(i + 1, nums, target, val, lst):
        return True
    if target == tot:
        val += 1
    lst.pop()
    return tracking( i + 1, nums, target, val, lst)


def split_odd_10(nums):
    """
    Given a list of ints, determine if the numbers can be split evenly into two groups
    The sum of one group must be odd, while the other group must be a multiple of 10
    Write a recursive helper to call from this function

    pre: len(nums) >= 0, nums will only contain ints
    post: return True if nums can be split, False otherwise
    """


def split_53(nums):
    """
    Given a list of ints, determine if the numbers can be split evenly into two groups
    The sum of these two groups must be equal
    Additionally, all multiples of 5 must be in one group, and all multiples of 3 (and not 5)
    must be in the other group
    Write a recursive helper to call from this function

    pre: len(nums) >= 0, nums will only contain ints
    post: return True if nums can be split, False otherwise
    """
    tots = sum(nums)
    val = 0
    lst_5 = []
    lst = []
    if tots % 2 == 0 and sum(nums) != 0:
        target = tots // 2
    elif sum(nums) == 0:
        return True
    else:
        return False
    return tracking_53(0, nums, target, val, lst, lst_5)


def tracking_53(i, nums, target, val, lst, lst_5):
    tot = sum(lst)
    if i >= len(nums):
        return val == 2
    if sum(lst) == sum(lst_5) and (sum(lst) + sum(lst_5)) != 0:
        return True
    if target == tot:
        val += 1
    if val == 2:
        return True

    if nums[i] % 5 == 0:
        lst_5.append(nums[i])
    elif nums[i] == 1 and sum(lst_5) > 0:
        lst_5.append(nums[i])
    else:
        lst.append(nums[i])
    if tracking_53(i + 1, nums, target, val, lst, lst_5):
        return True

    if target == tot:
        val += 1

    if sum(lst) > 0:
        lst.pop()
    if sum(lst_5) > 0:
        lst_5.pop()
    return tracking_53( i + 1, nums, target, val, lst, lst_5)
